### ISSUE TITLE
Obtaining the camera matrix

### ISSUE THREAD

**Issue by egrigokhan** [feliyur/big-bird-wrapper#1]
I'm trying to obtain the camera matrices for each view in order to construct a visual hull for the objects but I have so far only been able to find the `K` matrices for each camera. I was wondering how I can get the `R` and `t` matrices for each view from the calibration data.

**Comment by feliyur** [comment]
Hi, 

`calibration['H_NP{ii}_from_NP5']` is (somewhat unintuitively, but that's the dataset's notations) the transformation matrix from NP{ii} to NP5 coordinate system. Likewise, `poses[kk]['H_table_from_reference_camera']` is the transformation matrix from table coordinate system to NP5. Thus denoting the former T1 and the latter T2, the relative pose for view kk of camera ii is `inv(T2)*T1`, and from there you can extract R and t. 

Hope this helps. 
For myself I improved the wrapper functionality using [gtsam](https://github.com/borglab/gtsam), but didn't include it in the repo to avoid it as a dependency. If you're using gtsam I can send you the extended version. 

Yuri

**Comment by egrigokhan** [comment]
Thanks a lot!
